[tool.poetry]
name = "pet-project"
version = "0.1.0"
description = ""
authors = ["lomalo890 <george2066@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.8.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
