# Generated by Django 4.2.11 on 2024-10-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_create_play_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('start_at', models.DateTimeField()),
                ('actors', models.ManyToManyField(to='plays.actor')),
                (
                    'play',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.play'),
                ),
            ],
        ),
    ]
